### ISSUE TITLE
Response 403 from request

### ISSUE THREAD

**Issue by 8135tao** [jonchar/ma-scraper#2]
Hi, I am just getting into web-scraping and is experimenting with metal-archives.com. I just found your ma-scraper here and it looks super helpful for me to learn!

However, the code does not seems to be able to get data from MA right now (was working just a few days earlier, maybe because MA moved their data on a new server? from their homepage:  Maintenance / 2018-10-19 14:50
The site will be migrating to a new server tonight at midnight EDT / 4 am UTC. There will be some downtime. We'll try to make the process as quick and smooth as possible.
)

specifically, it seems that the problem is with
 `r = requests.get(BASEURL + RELURL + letter, params=payload)`,
that I am unable to get data by requests, it just returns
`<Response [403]>`
I absolutely have no idea how to make the scraper work at this point, so I was wondering someone more knowledgeable than me like you have an idea of what's going on.
Thank you very much for your work!

**Comment by 8135tao** [comment]
I asked on Stackoverflow
https://stackoverflow.com/questions/52941279/scraping-metal-archives-with-python,
now it is working fine, I will read more about the code now!

**Comment by jonchar** [comment]
Hi @8135tao! Thanks, I'm glad you've found the code useful!

I initially wrote this scraper about 3 years ago and haven't used it recently. Changes on their back end may have caused the scraper to break. If you do find a solution, pull requests are welcome :)
